//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjDemoEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiViet()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public string maBaiViet { get; set; }
        public string tuaBaiViet { get; set; }
        public string noiDungTomTat { get; set; }
        public string noiDungChinh { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public string maLoai { get; set; }
    
        public virtual LoaiBaiViet LoaiBaiViet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
